# Generated by Django 5.1.1 on 2024-11-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
